# Generated by Django 3.1.7 on 2021-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denuncia', '0003_auto_20210305_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='comentario',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('a', 'Dato/s falso/s en publicaciones'), ('b', 'Los animales no tienen todas las vacunas necesarias'), ('c', 'Sobreexplotación al animal hembra'), ('d', 'Maltrato animal')], max_length=1),
        ),
    ]
