# Generated by Django 3.1.7 on 2021-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0004_auto_20210307_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cantidad_de_mascotas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='especie',
            field=models.CharField(blank=True, choices=[('perro', 'Perro'), ('gato', 'Gato')], max_length=5),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
