# Generated by Django 3.1.7 on 2021-03-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0005_auto_20210307_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='cantidad_de_mascotas',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
