# Generated by Django 3.1.7 on 2021-03-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0009_auto_20210309_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='cantidad_de_mascotas',
        ),
        migrations.DeleteModel(
            name='Contador',
        ),
    ]
