# Generated by Django 3.1.7 on 2021-03-15 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publicacion', '0010_auto_20210314_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='edad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publicacion',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='usuario_futuro_duenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='descripcion',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
