# Generated by Django 3.1.7 on 2021-03-15 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0011_auto_20210314_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='nombre',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
