# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mensaje', '0002_auto_20210304_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='correo',
            new_name='chat',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='usuario_emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
