# Generated by Django 3.1.7 on 2021-03-16 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0012_publicacion_nombre'),
        ('mensaje', '0004_auto_20210307_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='mascota',
        ),
        migrations.AddField(
            model_name='chat',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion'),
        ),
    ]
