# Generated by Django 3.1.7 on 2021-03-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to='media')),
                ('especie', models.CharField(max_length=25)),
                ('sexo', models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=30)),
                ('raza', models.CharField(max_length=25)),
                ('edad', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.BooleanField(null=True)),
            ],
        ),
    ]
