# Generated by Django 3.1.7 on 2021-03-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
        ('publicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='publicacion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion'),
        ),
    ]
