# Generated by Django 3.1.7 on 2021-03-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0003_mascota_usuario_futuro_duenio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='usuario_futuro_duenio',
            new_name='usuario_duenio',
        ),
    ]
