# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mascota', '0005_auto_20210305_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='usuario_duenio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='usuario_futuro_duenio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
