# Generated by Django 3.1.7 on 2021-03-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0006_auto_20210307_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='estado',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(blank=True, choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=6),
        ),
    ]
