# Generated by Django 3.1.7 on 2021-03-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0008_auto_20210307_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(upload_to='media'),
        ),
    ]
