# Generated by Django 3.1.7 on 2021-03-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0009_auto_20210307_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='estado',
            field=models.BooleanField(null=True),
        ),
    ]
