# Generated by Django 3.1.7 on 2021-03-04 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id_postulante', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=250, null=True)),
                ('mascota_postulado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mascota.mascota')),
            ],
        ),
    ]
