# Generated by Django 3.1.7 on 2021-03-05 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0002_postulante_usuario_postulado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='usuario_postulado',
            new_name='usuario_p',
        ),
    ]
