# Generated by Django 3.1.7 on 2021-03-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postulante', '0003_auto_20210305_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='mascota_postulado',
            new_name='mascota',
        ),
        migrations.RemoveField(
            model_name='postulante',
            name='usuario_p',
        ),
        migrations.AddField(
            model_name='postulante',
            name='usuario_postulado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
