# Generated by Django 3.1.7 on 2021-03-11 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postulante', '0005_auto_20210307_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='comentario',
        ),
    ]
