# Generated by Django 3.1.7 on 2021-03-15 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publicacion', '0011_auto_20210314_2136'),
        ('postulante', '0006_remove_postulante_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='mascota',
        ),
        migrations.AddField(
            model_name='postulante',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='publicacion.publicacion'),
        ),
    ]
